--
-- define the lab table
-- 
-- To source this file from command line, issue:
--   beeline -u jdbc:hive2://ktphadoop.vsshp.net:10000/ktp
--   !run hive_table.sql

DROP TABLE IF EXISTS lab;

CREATE EXTERNAL TABLE IF NOT EXISTS lab (
  testid STRING,
  testp STRING,
  test STRING,
  testt INT,
  urgency INT,
  sampleid STRING,
  cost DOUBLE,
  fee DOUBLE,
  outcomet STRING,
  outcomen DOUBLE,
  unit STRING,
  microbe STRING,
  refmin DOUBLE,
  Refmax DOUBLE,
  refval DOUBLE,
  outsour STRING,
  weekday STRING,
  custorg0 STRING,
  custorg1 STRING,
  custorg2 STRING,
  custorg3 STRING,
  custorgt STRING,
  projid STRING,
  payer1 STRING,
  payer2 STRING,
  provorg1 STRING,
  labspecd STRING,
  labspec STRING,
  provorg2 STRING,
  testorg STRING,
  datetime1 TIMESTAMP,
  yy1v STRING,
  mm1 STRING,
  dd1 STRING,
  hh1 STRING,
  datetime2 TIMESTAMP,
  yy2 STRING,
  mm2 STRING,
  dd2 STRING,
  hh2 STRING,
  datetime3 TIMESTAMP,
  yy3 STRING,
  mm3 STRING,
  dd3 STRING,
  hh3 STRING,
  Datetime4 TIMESTAMP,
  yy4 STRING,
  mm4 STRING,
  dd4 STRING,
  hh4 STRING,
  Datetime5 TIMESTAMP,
  yy5 STRING,
  mm5 STRING,
  dd5 STRING,
  hh5 STRING,
  Datetime6 TIMESTAMP,
  yy6 STRING,
  mm6 STRING,
  dd6 STRING,
  hh6 STRING,
  Datetime7 TIMESTAMP,
  yy7 STRING,
  mm7 STRING,
  dd7 STRING,
  hh7 STRING,
  Delay1 STRING,
  Delay2 STRING,
  Delay3 STRING,
  Delay4 STRING,
  Delay5 STRING,
  Delay6 STRING,
  Macid STRING,
  Batchid STRING,
  Patidcode STRING,
  Agedays STRING,
  Ageyear STRING,
  Sex STRING,
  Patarea1 STRING,
  Spec STRING,
  Agecat1 STRING,
  Autoack STRING,
  dayt1 STRING,
  dayt2 STRING,
  dayt3 STRING,
  dayt4 STRING,
  dayt5 STRING,
  dayt6 STRING,
  dayt7 STRING,
  dayt8 STRING,
  macgrp STRING,
  testgrp STRING,
  agecat2 STRING,
  Agecat3 STRING,
  Hetu STRING,
  Mergeid STRING,
  datetime8 TIMESTAMP
)
PARTITIONED BY (dt STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';
-- LOCATION '/user/hive/warehouse/ktp/lab';
